### ISSUE TITLE
[frontend] rendering multiple cells as one when matrix becomes scrollable

### ISSUE THREAD

**Issue by abheektripathy** [availproject/light-client-web#30]
Currently when the data matrix exceeds a certain limit, the matrix rendered on the frontend becomes scrollable, we should have some logic that above a certain size, each cell in the frontend represents multiple cells rather than scrolling to see the full matrix + cells getting sampled.

**Comment by henryjindal112** [comment]
Please assign me @abheektripathy

**Comment by abheektripathy** [comment]
assigned @henryjindal112
