### ISSUE TITLE
[refactor] Switch from using polkadot-js to avail-js-sdk

### ISSUE THREAD

**Issue by abheektripathy** [availproject/light-client-web#32]
instead of using the polkadot js for getting the block headers, we can use [avail-js-sdk](https://npm.io/package/avail-js-sdk)

``` js
// example code which fetches the latest headers

import { initialize } from "avail-js-sdk"
const api = await initialize()
let lastHeader = (await api.rpc.chain.getHeader()).toJSON();
    console.log((lastHeader.extension));
console.log("subscribed headers", lastHeader) 
```

**Comment by cpp-phoenix** [comment]
I can pick this right away @abheektripathy until design is ready for the other issue

**Comment by abheektripathy** [comment]
@cpp-phoenix thanks, go for it!

**Comment by AryanGodara** [comment]
@abheektripathy are there going to be any new issues, with the ODHack week beginning today?
This past week I've been contributing in rollkit, and was getting onboarded with light-client-lib(rust) repo; and so I've been looking for a chance to contribute here.
I'd really be grateful if you could point me in the right direction :D
